services:
  fute:
    image: vini84200/fute:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./production/db:/usr/src/app/db
    user: 1000:1000
    environment:
      - COOKIE_KEY_MASTER=${DOCKER_COOKIE_KEY_MASTER}
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - LOCAL_DATABASE_URL=${DOCKER_LOCAL_DATABASE_URL}

networks:
  default:
    external: true
    name: net
