//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

// #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, EnumIter, DeriveActiveE

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ballot")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub players: Json,
    pub vote: Json,
    pub date: DateTimeUtc,
    pub voter: String,
    pub fute_id: i32,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub state: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
