//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "jogador")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub nome: String,
    pub apelido: String,
    pub email: String,
    pub senha_hash: String,
    pub admin: bool,
    #[sea_orm(column_type = "Blob", nullable)]
    pub imagem: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::lista_extra::Entity")]
    ListaExtra,
}

impl Related<super::lista_extra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ListaExtra.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
