//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "lista_extra")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub jogador_id: i32,
    pub data: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::jogador::Entity",
        from = "Column::JogadorId",
        to = "super::jogador::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Jogador,
}

impl Related<super::jogador::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Jogador.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
