//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::apuracao::Entity as Apuracao;
pub use super::ballot::Entity as Ballot;
pub use super::jogador::Entity as Jogador;
pub use super::lista_extra::Entity as ListaExtra;
